server:
  port: 4401
logging:
  config: classpath:logback-spring.xml
  file:
    max-history: 30
    max-size: 30MB
  path: logs/
spring:
  redis:
    host: m10043.mars.test.redis.ljnode.com
    port: 10043
    password: 61ceB83bfd